In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('raw_data/naukri_data_science_jobs_india.csv')

In [3]:
df.dtypes

Company                   str
Location                  str
education                 str
Skills/Description        str
job_type                  str
salary                float64
Job Experience            str
Job_Role                  str
dtype: object

In [4]:
df.head(3)

,Company,Location,education,Skills/Description,job_type,salary,Job Experience,Job_Role
0,UPL,"Bangalore/Bengaluru, Mumbai (All Areas)",Post-graduate,"python, MLT, statistical modeling, machine lea...",contract,939957.0,5-6,Senior Data Scientist
1,Walmart,Bangalore/Bengaluru,Post-graduate,"Data Science, Machine learning, Python, Azure,...",contract,2060767.0,1-7,Senior Data Scientist
2,SAP India Pvt.Ltd,Bangalore/Bengaluru,UG,"Python, IT Skills, Testing, Cloud, Product Man...",full-time,698970.0,7-8,Applied Data Scientist / ML Senior Engineer (P...

In [5]:
df.isnull().sum()

Company                  0
Location                 0
education             1676
Skills/Description       0
job_type              1280
salary                 976
Job Experience           0
Job_Role                 0
dtype: int64

In [6]:
df.describe()

             salary
count  1.102400e+04
mean   1.410455e+06
std    6.382235e+05
min    3.000220e+05
25%    8.637465e+05
50%    1.414624e+06
75%    1.966901e+06
max    2.499934e+06

In [9]:
df.shape

(12000, 8)

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Company             12000 non-null  str
 1   Location            12000 non-null  str
 2   education           10324 non-null  str
 3   Skills/Description  12000 non-null  str
 4   job_type            10720 non-null  str
 5   salary              11024 non-null  float64
 6   Job Experience      12000 non-null  str
 7   Job_Role            12000 non-null  str
dtypes: float64(1), str(7)
memory usage: 750.1 KB